import redShoes from "../../assets/img/png/redShoes.png";
import darkShoes from "../../assets/img/png/darkShoes.png";
import shopping from "../../assets/img/svg/shopping.svg";
import blackStar from "../../assets/img/svg/blackStarr.svg";
import positionImage from "../../assets/img/svg/positionImage.svg";
import positionImage1 from "../../assets/img/svg/positionImage1.svg";

export const mydata = [
  {
    img: redShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
  {
    img: darkShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
  {
    img: redShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
  {
    img: darkShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
  {
    img: redShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
  {
    img: darkShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
  {
    img: redShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
  {
    img: darkShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
  {
    img: redShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
  {
    img: darkShoes,
    img1: positionImage,
    img2: positionImage1,
    para: "Quickiins Mens Shoes",
    para1: " $90.00",
    span: " $70.00",
    img3: shopping,
    img4: blackStar,
  },
];
